### ISSUE TITLE
order favourites kodi version 21 omega

### ISSUE THREAD

**Issue by deputydoobie** [doko-desuka/plugin.program.orderfavourites#15]
hello looking for an updated version for kodi omega, leia works, however when ordering favourites  the first selection no longer assumes position left of the second selection, instead selections the switch.

**Comment by deputydoobie** [comment]
EDIT** matrix works, not leia

**Comment by doko-desuka** [comment]
@deputydoobie in the latest version, the ordering method was changed to "swap" instead of "re-insert". This is because swapping preserves the alignment of other items, while re-inserting might affect the alignment of many other items as explained in here: https://github.com/doko-desuka/plugin.program.orderfavourites/issues/10#issuecomment-1861211380

Also, you can mimic the old behavior by swapping with the item before the actual item you want to have in front.

**Comment by deputydoobie** [comment]
can you include an option for "re-insert" this "swap" method is rather inefficient on a mass scale when constantly adding new items

**Comment by doko-desuka** [comment]
> can you include an option for "re-insert" this "swap" method is rather inefficient on a mass scale when constantly adding new items

I left the old method commented out for anyone that wants to turn it back on. Then you can keep using your modified add-on instead of the official.  
The relevant lines are these:
https://github.com/doko-desuka/plugin.program.orderfavourites/blob/master/default.py#L119-L128

To turn it back on you need to change the script in a simple way:
- Using a desktop / notebook PC, download the add-on ZIP file and unpack it into some place. This will create a new folder: `/plugin.program.orderfavourites/`.
- Go into that folder and open `default.py` with some text editor (preferably a code editor, but Notepad will work fine).
- Uncomment (AKA remove the "#" symbol at the start of) the lines 121 and 122, thus enabling the old method.
- Comment (add the "#" to start of the first word of) the lines 126, 127 and 128, thus disabling the new method.
- Make sure that the empty spaces before words (called "indentation") is left untouched. You're really just adding or removing the "#" symbols.
- Save `default.py` to commit your changes.
- Zip the `/plugin.program.orderfavourites/` folder back into a ZIP file, just like it was before.
- Get this ZIP file into your Kodi device and use "Install from Zip" with this modified version.
- You'll only know if you made some error when you try to open the plugin (it'll error out with "Syntax error" or something like that), in which case you'll know you messed up somehow.
