### ISSUE TITLE
Installs but doesn't do anything

### ISSUE THREAD

**Issue by msauers** [doko-desuka/plugin.program.orderfavourites#3]
Windows 10, Kodi 18.9
Installed it just fine. Menu opens. But when I select "Order favourites..." nothing happens.
Any ideas?

**Comment by doko-desuka** [comment]
Hi @msauers,
if the main menu appears then at least the add-on is loading properly. So it fails when you select "Order Favourites...", which is when the popup dialog would show.

Can you turn on the Kodi Debug mode and send me your Kodi log? it should say why it's failing.

**Comment by doko-desuka** [comment]
(`Enable debug logging` can be seen here: https://kodi.wiki/view/Settings/System/Logging)

**Comment by msauers** [comment]
Turned on logging. Opened plugin. Attempted to sort. Exited plugin. Turned off logging. Results attached.
[Attachment removed]

**Comment by doko-desuka** [comment]
Thanks for the log in Debug mode.  
Your log says that you have the latest OrderFavourites version installed, v1.1.1, as it should be.

The add-on is failing in some unexpected way (I don't know in what way though, because I didn't add proper logging code that explains any errors that come up). Maybe it's failing when trying to load the favourites file.  

Can you try this modified version below?
[plugin.program.orderfavourites-1.1.12.zip](https://github.com/doko-desuka/plugin.program.orderfavourites/files/5504585/plugin.program.orderfavourites-1.1.12.zip)  
Turning on Debug mode is not necessary this time, as script errors will always show on the log. Then we can see where it's failing.  

Also, would you mind sharing the favourites file itself, so I can run some tests? The file is called [Favourites.xml](https://kodi.wiki/view/Favourites.xml) and is in your [userdata folder](https://kodi.wiki/view/Userdata#Location) (the path to it varies by device).

**Comment by msauers** [comment]
Installed updated version. This time Kodi did show a non-descript error message. Here's my favorites file & new log.
[Attachment removed]

**Comment by doko-desuka** [comment]
@msauers thank you so much for the supplemental files. (You can safely delete your comments so the attachments don't stay uploaded.)

Here's the fixed add-on: [plugin.program.orderfavourites-1.2.0.zip](https://github.com/doko-desuka/doko.repository/raw/master/plugin.program.orderfavourites/plugin.program.orderfavourites-1.2.0.zip)

**Comment by msauers** [comment]
The new version works. Thanks!
